//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Errors
{
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;

    public class ErrorUnauthorizedPayload
    {
        /// <summary>
        /// A list of errors that occurred.
        /// </summary>
        [JsonProperty("errors")]
        public List<ErrorUnauthorizedError> Errors { get; set; } = default!;

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    /// <summary>
    /// Invalid authentication credentials.
    /// </summary>
    public class ErrorUnauthorized : DailyPayError
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public ErrorUnauthorizedPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use ErrorUnauthorized.Payload.Errors instead.")]
        public List<ErrorUnauthorizedError> Errors { get; set; } = default!;

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use ErrorUnauthorized.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        public ErrorUnauthorized(
            ErrorUnauthorizedPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base("API error occurred", request, response, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Errors = payload.Errors;
           HttpMeta = payload.HttpMeta;
           #pragma warning restore CS0618
        }
    }
}