//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Utils;
    using Newtonsoft.Json;
    
    public class AccountAttributesDepositoryAccountBalances
    {

        /// <summary>
        /// The amount of funds available to be withdrawn from the account. <br/>
        /// 
        /// <remarks>
        /// <br/>
        /// For earnings_balance-type accounts, the available balance typically<br/>
        /// equals the current balance less any pending outflows, plus any pending inflows,<br/>
        /// <br/>
        /// <br/>
        /// This value is in units of the lowest denomination in the associated<br/>
        /// currency. For example, `{ amount: 7250, currency: &apos;USD&apos; }` resolves to<br/>
        /// $72.50.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("available", NullValueHandling = NullValueHandling.Include)]
        public long? Available { get; set; }

        /// <summary>
        /// The total amount of funds settled in the account. <br/>
        /// 
        /// <remarks>
        /// <br/>
        /// This value is in units of the lowest denomination in the associated<br/>
        /// currency. For example, `{ amount: 7250, currency: &apos;USD&apos; }` resolves to<br/>
        /// $72.50.<br/>
        /// <br/>
        /// <br/>
        /// **Special note for earnings_balance-type accounts:**<br/>
        /// During a typical pay period, if a user transfers no money from an earnings_balance-type account to a personal account, <br/>
        /// the `current` balance will generally be 0, because transfers from earnings to this account will be <br/>
        /// PENDING until the paycheck related to those earnings is processed. <br/>
        /// Pending inflows are included in the `available` balance, not the `current` balance.<br/>
        ///  <br/>
        /// If a user transfers money from an earnings_balance-type account to a personal account, <br/>
        /// the `current` balance will be negative as those transfers settle. When a paycheck is processed, <br/>
        /// DailyPay will automatically attempt to zero out the balance, <br/>
        /// transferring any remaining funds to the `default_paycheck_destination` set for the associated Job.<br/>
        /// <br/>
        /// If DailyPay is unable to zero out the balance during paycheck processing, the `current` balance will remain negative, <br/>
        /// which may impact a user&apos;s ability to transfer additional funds from their earnings balance. <br/>
        /// In those cases, the available balance will be 0.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("current", NullValueHandling = NullValueHandling.Include)]
        public long? Current { get; set; }

        /// <summary>
        /// A three-letter ISO 4217 currency code. For example, `USD` for US Dollars, `EUR` for Euros, or `JPY` for Japanese Yen.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; } = default!;
    }
}