//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Utils;
    using Newtonsoft.Json;
    
    public class AccountWiselyCard
    {

        /// <summary>
        /// The first name of the account holder.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName { get; set; } = default!;

        /// <summary>
        /// The last name of the account holder.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName { get; set; } = default!;

        /// <summary>
        /// The month of the expiration date for the card.
        /// </summary>
        [JsonProperty("expiration_month")]
        public string ExpirationMonth { get; set; } = default!;

        /// <summary>
        /// The year of the expiration date for the card.
        /// </summary>
        [JsonProperty("expiration_year")]
        public string ExpirationYear { get; set; } = default!;

        /// <summary>
        /// The first line of the address for the card.
        /// </summary>
        [JsonProperty("address_line_one")]
        public string AddressLineOne { get; set; } = default!;

        /// <summary>
        /// The second line of the address for the card.
        /// </summary>
        [JsonProperty("address_line_two")]
        public string? AddressLineTwo { get; set; }

        /// <summary>
        /// The city of the address for the card.
        /// </summary>
        [JsonProperty("address_city")]
        public string AddressCity { get; set; } = default!;

        /// <summary>
        /// The two-letter abbreviation of the state in the address for the card.
        /// </summary>
        [JsonProperty("address_state")]
        public string AddressState { get; set; } = default!;

        /// <summary>
        /// The zip code of the address for the card.
        /// </summary>
        [JsonProperty("address_zip_code")]
        public string AddressZipCode { get; set; } = default!;

        /// <summary>
        /// The country code of the address for the card.
        /// </summary>
        [JsonProperty("address_country")]
        public string AddressCountry { get; set; } = default!;

        /// <summary>
        /// Wisely unique identifier associated to card.
        /// </summary>
        [JsonProperty("wisely_token")]
        public string WiselyToken { get; set; } = default!;

        /// <summary>
        /// Last four digits of the card number.
        /// </summary>
        [JsonProperty("last_four")]
        public string LastFour { get; set; } = default!;

        /// <summary>
        /// The issuer of the card.
        /// </summary>
        [JsonProperty("issuer")]
        public string Issuer { get; set; } = default!;
    }
}