//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Models.Components;
    using DailyPay.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An account with type `DEPOSITORY` and subtype `SAVINGS` or `CHECKING`.
    /// </summary>
    public class DepositoryInput
    {

        /// <summary>
        /// Display name for this account.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// The type of account. It differentiates between depository accounts (e.g. bank account), cards (e.g. debit) and earnings balance type of accounts (e.g. on demand pay).
        /// </summary>
        [JsonProperty("account_type")]
        public string AccountType { get; } = "DEPOSITORY";

        /// <summary>
        /// The subtype of the account.
        /// </summary>
        [JsonProperty("subtype")]
        public AccountAttributesDepositorySubtype Subtype { get; set; } = default!;

        /// <summary>
        /// The banking details of the account and account holder.
        /// </summary>
        [JsonProperty("details")]
        public DepositoryAccountDetails DepositoryAccountDetails { get; set; } = default!;
    }
}