//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Utils;
    
    /// <summary>
    /// An account with type `EARNINGS_BALANCE` and subtype `ODP`.
    /// </summary>
    public class EarningsBalanceReadOnlyInput
    {
    }
}