//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Additional information about the error.
    /// </summary>
    public class ErrorForbiddenErrorMeta
    {

        /// <summary>
        /// A UUID for the originating request.
        /// </summary>
        [JsonProperty("request_id")]
        public string? RequestId { get; set; }

        /// <summary>
        /// An ID used for tracing purposes.
        /// </summary>
        [JsonProperty("trace_id")]
        public string? TraceId { get; set; }
    }
}