//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Utils;
    using Newtonsoft.Json;
    using System;
    
    public enum Frequency
    {
        [JsonProperty("HOURLY")]
        Hourly,
        [JsonProperty("WEEKLY")]
        Weekly,
        [JsonProperty("BIWEEKLY")]
        Biweekly,
        [JsonProperty("TWICE_MONTHLY")]
        TwiceMonthly,
        [JsonProperty("MONTHLY")]
        Monthly,
        [JsonProperty("ANNUALLY")]
        Annually,
    }

    public static class FrequencyExtension
    {
        public static string Value(this Frequency value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Frequency ToEnum(this string value)
        {
            foreach(var field in typeof(Frequency).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Frequency)
                    {
                        return (Frequency)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Frequency");
        }
    }

}