//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Models.Components;
    using DailyPay.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// The relationships between the transfer and other resources, including the destination account, the origination account, and the person who initiated the transfer.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class TransferRelationships
    {

        /// <summary>
        /// Origin may be a reference to either a Paycheck or an Account.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// User-created transfers always originate from an Account with `account_type` `EARNINGS_BALANCE`.<br/>
        /// <br/>
        /// A transfer that originates from a Paycheck is a  <br/>
        /// system-created record that describes a credit of earnings to an account with `account_type` `EARNINGS_BALANCE`.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("origin")]
        public Origin Origin { get; set; } = default!;

        [JsonProperty("destination")]
        public AccountRelationship Destination { get; set; } = default!;

        [JsonProperty("person")]
        public PersonRelationship Person { get; set; } = default!;

        [JsonProperty("estimated_funding_sources")]
        public FundingSourcesRelationship EstimatedFundingSources { get; set; } = default!;

        [JsonProperty("final_funding_sources")]
        public FundingSourcesRelationship FinalFundingSources { get; set; } = default!;
    }
}