//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Models.Components;
    using DailyPay.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Returns the newly created transfer object.
    /// </summary>
    public class TransferData
    {

        [JsonProperty("data")]
        public TransferResource Data { get; set; } = default!;

        [JsonProperty("included")]
        public List<FundingSourceResource>? Included { get; set; }
    }
}