//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Dotnet9.Models.Errors
{
    using DailyPay.Dotnet9.Models.Components;
    using DailyPay.Dotnet9.Models.Requests;
    using DailyPay.Dotnet9.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Something went wrong when exchanging oauth grant or refresh token for an access token. NOTE: This conforms to the OAuth spec and does not follow the same error pattern as the rest of the API
    /// </summary>
    public class BadRequestException : Exception
    {

        /// <summary>
        /// Error code indicating what went wrong with the oauth token exchange. See the OAuth2 RFC for further context https://datatracker.ietf.org/doc/html/rfc6749#section-5.2
        /// </summary>
        [JsonProperty("error_code")]
        public ErrorCode? ErrorCode { get; set; }

        /// <summary>
        /// A description of exactly went wrong with the oauth token exchange. This is meant to improve developer experience, and is subject to change, so this should not be relied upon programatically.
        /// </summary>
        [JsonProperty("error_description")]
        public string? ErrorDescription { get; set; }

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }
}