//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Requests
{
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Returns an opaque string representing the card details.
    /// </summary>
    public class CreateGenericCardTokenResponseBody
    {
        /// <summary>
        /// This token should be supplied in the `generic_token` field when creating a TransferAccount with <br/>
        /// `transfer_account_type` of DebitCard using the Extend API "Create a transfer account" endpoint.
        /// </summary>
        [JsonProperty("token")]
        public string Token { get; set; } = default!;
    }
}