//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Requests
{
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;

    public class CreateGenericCardTokenRequest
    {
        /// <summary>
        /// The first name or given name of the cardholder.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName { get; set; } = default!;

        /// <summary>
        /// The last name or surname of the cardholder.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName { get; set; } = default!;

        /// <summary>
        /// The full card number without spaces or hyphenation.
        /// </summary>
        [JsonProperty("card_number")]
        public string CardNumber { get; set; } = default!;

        /// <summary>
        /// The four-digit year of expiration for the card.
        /// </summary>
        [JsonProperty("expiration_year")]
        public string ExpirationYear { get; set; } = default!;

        /// <summary>
        /// The two-digit month of the expiration date for the card.
        /// </summary>
        [JsonProperty("expiration_month")]
        public string ExpirationMonth { get; set; } = default!;

        /// <summary>
        /// The CVV card code.
        /// </summary>
        [JsonProperty("cvv")]
        public string? Cvv { get; set; } = null;

        /// <summary>
        /// The first line of the address associated with the card.
        /// </summary>
        [JsonProperty("address_line_one")]
        public string AddressLineOne { get; set; } = default!;

        /// <summary>
        /// The second line of the address associated with the card.
        /// </summary>
        [JsonProperty("address_line_two")]
        public string? AddressLineTwo { get; set; } = null;

        /// <summary>
        /// The city component of the address associated with the card.
        /// </summary>
        [JsonProperty("address_city")]
        public string AddressCity { get; set; } = default!;

        /// <summary>
        /// The two-letter state component of the address associated with the card.
        /// </summary>
        [JsonProperty("address_state")]
        public string AddressState { get; set; } = default!;

        /// <summary>
        /// The 5 digit zip-code component of the address associated with the card.
        /// </summary>
        [JsonProperty("address_zip_code")]
        public string AddressZipCode { get; set; } = default!;

        /// <summary>
        /// The two-letter ISO 3166 country code component of the address associated with the card.
        /// </summary>
        [JsonProperty("address_country")]
        public string AddressCountry { get; set; } = default!;
    }
}