//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Requests
{
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Utils;
    using System;

    public class ListPaychecksRequest
    {
        /// <summary>
        /// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=DailyPay-API-Version")]
        public long? Version { get; set; } = 3;

        /// <summary>
        /// Limit the results to documents related to a specific job.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[job.id]")]
        public string? FilterJobId { get; set; }

        /// <summary>
        /// Limit the results to paychecks with the specified status.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[status]")]
        public FilterPaycheckStatus? FilterStatus { get; set; }

        /// <summary>
        /// Limit the results to paychecks with deposit_expected_at greater than or equal to the specified date.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[deposit_expected_at__gte]")]
        public DateTime? FilterDepositExpectedAtGte { get; set; }

        /// <summary>
        /// Limit the results to paychecks with deposit_expected_at less than the specified date.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[deposit_expected_at__lt]")]
        public DateTime? FilterDepositExpectedAtLt { get; set; }

        /// <summary>
        /// Limit the results to paychecks with pay_period_ends_at greater than or equal to the specified date.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[pay_period_ends_at__gte]")]
        public DateTime? FilterPayPeriodEndsAtGte { get; set; }

        /// <summary>
        /// Limit the results to paychecks with pay_period_ends_at less than the specified date.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[pay_period_ends_at__lt]")]
        public DateTime? FilterPayPeriodEndsAtLt { get; set; }

        /// <summary>
        /// Limit the results to paychecks with pay_period_starts_at greater than or equal to the specified date.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[pay_period_starts_at__gte]")]
        public DateTime? FilterPayPeriodStartsAtGte { get; set; }

        /// <summary>
        /// Limit the results to paychecks with pay_period_starts_at less than the specified date.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[pay_period_starts_at__lt]")]
        public DateTime? FilterPayPeriodStartsAtLt { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")]
        public string? FilterBy { get; set; }
    }
}