//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Requests
{
    using DailyPay.SDK.DotNet9.Utils;
    
    public class ReadPaycheckRequest
    {

        /// <summary>
        /// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=DailyPay-API-Version")]
        public long? Version { get; set; } = 3;

        /// <summary>
        /// Unique ID of the paycheck
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=paycheck_id")]
        public string PaycheckId { get; set; } = default!;
    }
}