//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Requests
{
    using DailyPay.SDK.DotNet9.Utils;
    
    public class RefreshToken
    {

        /// <summary>
        /// The OAuth2 grant type
        /// </summary>
        [SpeakeasyMetadata("form:name=grant_type")]
        public string GrantType { get; set; } = default!;

        /// <summary>
        /// A refresh token received from a previous token request
        /// </summary>
        [SpeakeasyMetadata("form:name=refresh_token")]
        public string RefreshTokenValue { get; set; } = default!;

        /// <summary>
        /// The client id of the application requesting the token.
        /// </summary>
        [SpeakeasyMetadata("form:name=client_id")]
        public string ClientId { get; set; } = default!;

        /// <summary>
        /// The client secret of the application requesting the token, if available.
        /// </summary>
        [SpeakeasyMetadata("form:name=client_secret")]
        public string? ClientSecret { get; set; }
    }
}