//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using Openapi.Utils;
    using System.Collections.Generic;
    
    public class AccountAttributesDepositoryAccountCapabilities
    {

        /// <summary>
        /// List of the timing and associate fees available when crediting this account as a<br/>
        /// 
        /// <remarks>
        /// transfer destination.<br/>
        /// <br/>
        /// Actual fees may differ at the time of transfer; please refer to <br/>
        /// the transfer preview attribute for the most accurate fee information <br/>
        /// for any given transfer. <br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("transfer_destination")]
        public List<TransferDestinationCapability> TransferDestination { get; set; } = default!;
    }
}