//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    
    public class AccountDebitCardOutput
    {

        /// <summary>
        /// The first name of the account holder.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName { get; set; } = default!;

        /// <summary>
        /// The last name of the account holder.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName { get; set; } = default!;

        /// <summary>
        /// The month of the expiration date for the card.
        /// </summary>
        [JsonProperty("expiration_month")]
        public string ExpirationMonth { get; set; } = default!;

        /// <summary>
        /// The year of the expiration date for the card.
        /// </summary>
        [JsonProperty("expiration_year")]
        public string ExpirationYear { get; set; } = default!;

        /// <summary>
        /// Last four digits of the card number.
        /// </summary>
        [JsonProperty("last_four")]
        public string LastFour { get; set; } = default!;

        /// <summary>
        /// The issuer of the card.
        /// </summary>
        [JsonProperty("issuer")]
        public string Issuer { get; set; } = default!;
    }
}