//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    
    /// <summary>
    /// The banking details of the account and account holder.
    /// </summary>
    public class DepositoryAccountDetails
    {

        /// <summary>
        /// The first name of the account holder.
        /// </summary>
        [JsonProperty("first_name")]
        public string FirstName { get; set; } = default!;

        /// <summary>
        /// The last name of the account holder.
        /// </summary>
        [JsonProperty("last_name")]
        public string LastName { get; set; } = default!;

        /// <summary>
        /// The routing number of the bank that holds this account. Responses from this API that return this number are masked to the last four digits.
        /// </summary>
        [JsonProperty("routing_number")]
        public string RoutingNumber { get; set; } = default!;

        /// <summary>
        /// The account number. Responses from this API that return this number are masked to the last four digits.
        /// </summary>
        [JsonProperty("account_number")]
        public string AccountNumber { get; set; } = default!;
    }
}