//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using Openapi.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// A list of transfer objects.
    /// </summary>
    public class TransfersData
    {

        [JsonProperty("data")]
        public List<TransferResource> Data { get; set; } = default!;

        [JsonProperty("included")]
        public List<FundingSourceResource>? Included { get; set; }
    }
}