//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Components
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using Openapi.Utils;
    
    /// <summary>
    /// The relationships between the transfer and other resources, including the destination account, the origination account, and the person who initiated the transfer.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class TransferCreateRelationships
    {

        [JsonProperty("origin")]
        public AccountRelationship Origin { get; set; } = default!;

        [JsonProperty("destination")]
        public AccountRelationship Destination { get; set; } = default!;

        [JsonProperty("person")]
        public PersonRelationship Person { get; set; } = default!;
    }
}