//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Requests
{
    using DailyPay.Utils;
    
    public class ReadAccountRequest
    {

        /// <summary>
        /// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=DailyPay-API-Version")]
        public long? Version { get; set; } = 3;

        /// <summary>
        /// Unique UUID of the Account.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=account_id")]
        public string AccountId { get; set; } = default!;
    }
}