//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Dotnet9.Models.Requests
{
    using DailyPay.Dotnet9.Models.Components;
    using DailyPay.Dotnet9.Utils;
    
    public class CreateTransferRequest
    {

        /// <summary>
        /// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=DailyPay-API-Version")]
        public long? Version { get; set; } = 3;

        /// <summary>
        /// An idempotency key is a unique string that you provide to ensure a request is only processed once.<br/>
        /// 
        /// <remarks>
        /// Any number of requests with the same idempotency key and payload will return an identical response.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=Idempotency-Key")]
        public string IdempotencyKey { get; set; } = default!;

        /// <summary>
        /// Add related resources to the response. <br/>
        /// 
        /// <remarks>
        /// <br/>
        /// The value of the include parameter must be a comma-separated (U+002C COMMA, “,”) list of relationship paths.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=include")]
        public string? Include { get; set; }

        [SpeakeasyMetadata("request:mediaType=application/vnd.api+json")]
        public TransferCreateData TransferCreateData { get; set; } = default!;
    }
}