//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Openapi.Utils;
    
    public class ClientCredentialsFlow
    {

        /// <summary>
        /// The OAuth2 grant type
        /// </summary>
        [SpeakeasyMetadata("form:name=grant_type")]
        public string GrantType { get; set; } = default!;

        /// <summary>
        /// A space-separated list of scopes to request
        /// </summary>
        [SpeakeasyMetadata("form:name=scope")]
        public string Scope { get; set; } = default!;

        /// <summary>
        /// The client id of the application requesting the token.
        /// </summary>
        [SpeakeasyMetadata("form:name=client_id")]
        public string ClientId { get; set; } = default!;

        /// <summary>
        /// The client secret of the application requesting the token.
        /// </summary>
        [SpeakeasyMetadata("form:name=client_secret")]
        public string ClientSecret { get; set; } = default!;
    }
}