//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Requests
{
    using Newtonsoft.Json;
    using Openapi.Utils;
    
    /// <summary>
    /// Returns an opaque string representing the card details.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    public class CreateGenericCardTokenResponseBody
    {

        /// <summary>
        /// This token should be supplied in the `generic_token` field when creating a TransferAccount with <br/>
        /// 
        /// <remarks>
        /// `transfer_account_type` of DebitCard using the Extend API &quot;Create a transfer account&quot; endpoint.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("token")]
        public string Token { get; set; } = default!;
    }
}