//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Dotnet9.Models.Components
{
    using DailyPay.Dotnet9.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// An account of type CARD with subtype GALILEO.
    /// </summary>
    public class AccountGalileoCardInput
    {

        /// <summary>
        /// The card ID provided by Galileo.
        /// </summary>
        [JsonProperty("galileo_card_id")]
        public string GalileoCardId { get; set; } = default!;

        /// <summary>
        /// The payment reference number provided by Galileo.
        /// </summary>
        [JsonProperty("galileo_pmt_ref_no")]
        public string GalileoPmtRefNo { get; set; } = default!;
    }
}