//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Dotnet9.Models.Components
{
    using DailyPay.Dotnet9.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// A code that indicates the status of an account that is a destination for funds.
    /// </summary>
    public enum AccountAttributesDepositoryVerificationStatus
    {
        [JsonProperty("VERIFICATION_PENDING")]
        VerificationPending,
        [JsonProperty("VERIFICATION_FAILED")]
        VerificationFailed,
        [JsonProperty("VERIFIED")]
        Verified,
    }

    public static class AccountAttributesDepositoryVerificationStatusExtension
    {
        public static string Value(this AccountAttributesDepositoryVerificationStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AccountAttributesDepositoryVerificationStatus ToEnum(this string value)
        {
            foreach(var field in typeof(AccountAttributesDepositoryVerificationStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AccountAttributesDepositoryVerificationStatus)
                    {
                        return (AccountAttributesDepositoryVerificationStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AccountAttributesDepositoryVerificationStatus");
        }
    }

}