//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Dotnet9.Models.Components
{
    using DailyPay.Dotnet9.Models.Components;
    using DailyPay.Dotnet9.Utils;
    using Newtonsoft.Json;
    
    public class ErrorTransferCreateError
    {

        /// <summary>
        /// A code that indicates what went wrong. Please consider this an open enum, where new codes may be added over time.
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; } = default!;

        /// <summary>
        /// The HTTP status code for the error.
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; } = default!;

        /// <summary>
        /// A message that explains the meaning of the error code. Developers are advised not to make programmatic use of this value, as it may change
        /// </summary>
        [JsonProperty("detail")]
        public string Detail { get; set; } = default!;

        /// <summary>
        /// A list of links to resources that may be helpful in resolving the error.
        /// </summary>
        [JsonProperty("links")]
        public ErrorTransferCreateErrorLinks Links { get; set; } = default!;

        /// <summary>
        /// Location in the request that may have caused the error.
        /// </summary>
        [JsonProperty("source")]
        public ErrorTransferCreateErrorSource? Source { get; set; }

        /// <summary>
        /// Additional information about the error.
        /// </summary>
        [JsonProperty("meta")]
        public ErrorTransferCreateErrorMeta Meta { get; set; } = default!;
    }
}