//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Dotnet9.Models.Components
{
    using DailyPay.Dotnet9.Models.Components;
    using DailyPay.Dotnet9.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// A job describes the financial relationship between a person and an organization.
    /// </summary>
    public class JobResource
    {

        [JsonProperty("type")]
        public string Type { get; } = "jobs";

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("attributes")]
        public JobAttributes Attributes { get; set; } = default!;

        [JsonProperty("links")]
        public JobLinks Links { get; set; } = default!;

        /// <summary>
        /// The relationships between the job and other resources, including the accounts to which paychecks from this job are deposited.
        /// </summary>
        [JsonProperty("relationships")]
        public JobRelationships Relationships { get; set; } = default!;
    }
}