//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Dotnet9.Models.Components
{
    using DailyPay.Dotnet9.Models.Components;
    using DailyPay.Dotnet9.Utils;
    using Newtonsoft.Json;
    
    public class TransferResource
    {

        [JsonProperty("type")]
        public string Type { get; } = "transfers";

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// An object representing a transfer of money from one account to another. <br/>
        /// 
        /// <remarks>
        /// Created when a person takes an advance against a future paycheck, or on a daily basis <br/>
        /// when we update estimated earnings based on current employment.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("attributes")]
        public TransferAttributes Attributes { get; set; } = default!;

        [JsonProperty("links")]
        public TransferLinks Links { get; set; } = default!;

        [JsonProperty("relationships")]
        public TransferRelationships Relationships { get; set; } = default!;
    }
}