workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    local:
        inputs:
            - location: https://s3.amazonaws.com/dp-devportal-images/oas/openapi.yml
        registry:
            location: registry.speakeasyapi.dev/dailypay/dailypay/xapi
targets:
    csharp-9:
        target: csharp
        source: local
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/dailypay/dailypay/xapi
