//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Hooks
{
    using System;
    using Newtonsoft.Json;

    /// <summary>
    /// Available scopes for the oauth_client_credentials_token OAuth 2.0 scheme (clientCredentials flow).
    /// </summary>
    public enum OauthClientCredentialsTokenOAuth2Scope
    {

        /// <summary>
        /// Read access to resources necessary to find a person by known identifiers.
        /// </summary>
        [JsonProperty("client:lookup")]
        ClientLookup,
    }


    public static class OauthClientCredentialsTokenOAuth2ScopeExtension
    {
        public static string Value(this OauthClientCredentialsTokenOAuth2Scope value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OauthClientCredentialsTokenOAuth2Scope ToEnum(this string value)
        {
            foreach(var field in typeof(OauthClientCredentialsTokenOAuth2Scope).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OauthClientCredentialsTokenOAuth2Scope)
                    {
                        return (OauthClientCredentialsTokenOAuth2Scope)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OauthClientCredentialsTokenOAuth2Scope");
        }
    }

    /// <summary>
    /// Available scopes for the oauth_user_token OAuth 2.0 scheme (authorizationCode flow).
    /// </summary>
    public enum OauthUserTokenOAuth2Scope
    {

        /// <summary>
        /// Read access to all relevant objects for a non-application user,  including accounts, jobs, people, transfers, and paychecks.
        /// </summary>
        [JsonProperty("user:read")]
        UserRead,

        /// <summary>
        /// Read and write access to all relevant objects for a non-application user, including accounts, jobs, people, transfers, and paychecks.
        /// </summary>
        [JsonProperty("user:read_write")]
        UserReadWrite,
    }


    public static class OauthUserTokenOAuth2ScopeExtension
    {
        public static string Value(this OauthUserTokenOAuth2Scope value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static OauthUserTokenOAuth2Scope ToEnum(this string value)
        {
            foreach(var field in typeof(OauthUserTokenOAuth2Scope).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is OauthUserTokenOAuth2Scope)
                    {
                        return (OauthUserTokenOAuth2Scope)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum OauthUserTokenOAuth2Scope");
        }
    }
}
