//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9
{
    using DailyPay.SDK.DotNet9.Hooks;
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Models.Errors;
    using DailyPay.SDK.DotNet9.Utils;
    using DailyPay.SDK.DotNet9.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading.Tasks;


    public enum ServerEnvironment
    {
        [JsonProperty("dailypay")]
        Dailypay,
        [JsonProperty("dailypayuat")]
        Dailypayuat,
    }

    public static class ServerEnvironmentExtension
    {
        public static string Value(this ServerEnvironment value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ServerEnvironment ToEnum(this string value)
        {
            foreach(var field in typeof(ServerEnvironment).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ServerEnvironment)
                    {
                        return (ServerEnvironment)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ServerEnvironment");
        }
    }

    /// <summary>
    /// DailyPay Rest API: Embed DailyPay and On Demand Pay features into your application.
    /// </summary>
    public interface ISDK
    {

        /// <summary>
        /// The _jobs_ endpoint provides access to comprehensive information <br/>
        /// 
        /// <remarks>
        /// about a person&apos;s employment. It enables you to retrieve details about<br/>
        /// individual jobs, including information about the organization<br/>
        /// they work for, status, wage rate, job title, location,<br/>
        /// paycheck settings, and related links to associated accounts.<br/>
        /// 
        /// </remarks>
        /// </summary>
        public IJobs Jobs { get; }

        /// <summary>
        /// The _accounts_ endpoint provides comprehensive information about money<br/>
        /// 
        /// <remarks>
        /// accounts. You can retrieve account details, including the<br/>
        /// account&apos;s unique ID, a link to the account holder, type, subtype,<br/>
        /// verification status, balance details, transfer capabilities, and<br/>
        /// user-specific information such as names, routing numbers, and partial<br/>
        /// account numbers.<br/>
        /// <br/>
        /// <br/>
        /// **Functionality:** Access detailed user account information, verify<br/>
        /// account balances, view transfer capabilities, and access user-specific<br/>
        /// details associated with each account.<br/>
        /// 
        /// </remarks>
        /// </summary>
        public IAccounts Accounts { get; }

        /// <summary>
        /// The _transfers_ endpoint allows you to initiate and track money movement.  You can access transfer details, including the transfer&apos;s unique ID, amount, currency, status, schedule, submission and resolution times, fees, and related links to the involved parties.<br/>
        /// 
        /// <remarks>
        /// <br/>
        /// **Functionality** Retrieve transfer information, monitor transfer statuses, view transfer schedules, and access relevant links for the source, destination, and origin of the transfer.<br/>
        /// <br/>
        /// **Important** - Account origin: a user initiated movement of money from one account to another - Paycheck origin: an automatic (system-generated) movement of money as part of payroll<br/>
        /// 
        /// </remarks>
        /// </summary>
        public ITransfers Transfers { get; }

        /// <summary>
        /// The _paychecks_ endpoint provides detailed information about paychecks. <br/>
        /// 
        /// <remarks>
        /// You can retrieve individual paycheck details, including the<br/>
        /// person and job associated with the paycheck, its status, pay period,<br/>
        /// expected deposit date, total debited amount, withholdings, earnings, and<br/>
        /// currency.<br/>
        /// <br/>
        /// **Functionality:** Retrieve specific paycheck details, including payee and<br/>
        /// job information, and monitor the status and financial details of each<br/>
        /// paycheck.<br/>
        /// 
        /// </remarks>
        /// </summary>
        public IPaychecks Paychecks { get; }

        /// <summary>
        /// The _organizations_ endpoint provides details about a business entity, <br/>
        /// 
        /// <remarks>
        /// such as an employer, or a group of people, such as a division.<br/>
        /// <br/>
        /// The response includes the organization name and ID which can be used to<br/>
        /// make subsequent endpoint calls related to the organization and its<br/>
        /// employees.<br/>
        /// 
        /// </remarks>
        /// </summary>
        public IOrganizations Organizations { get; }

        /// <summary>
        /// The _people_ endpoint allows you to see information related to who owns <br/>
        /// 
        /// <remarks>
        /// resources such as jobs and accounts.<br/>
        /// <br/>
        /// **Functionality:** Retrieve limited details about a person, including<br/>
        /// their name, global status, and state of residence.<br/>
        /// 
        /// </remarks>
        /// </summary>
        public IPeople People { get; }

        /// <summary>
        /// Securely tokenize personal cards for use in the accounts API.
        /// </summary>
        public ICardTokenization CardTokenization { get; }

        /// <summary>
        /// The _health_ endpoint provides a simple health check for the API. <br/>
        /// 
        /// <remarks>
        /// <br/>
        /// **Functionality:** Check the status of the API to ensure it is functioning<br/>
        /// correctly.<br/>
        /// 
        /// </remarks>
        /// </summary>
        public IHealth Health { get; }
    }


    /// <summary>
    /// DailyPay Rest API: Embed DailyPay and On Demand Pay features into your application.
    /// </summary>
    public class SDK: ISDK
    {
        public SDKConfig SDKConfiguration { get; private set; }

        private const string _language = "csharp";
        private const string _sdkVersion = "0.5.4";
        private const string _sdkGenVersion = "2.755.9";
        private const string _openapiDocVersion = "3.0.0-beta88";
        public IJobs Jobs { get; private set; }
        public IAccounts Accounts { get; private set; }
        public ITransfers Transfers { get; private set; }
        public IPaychecks Paychecks { get; private set; }
        public IOrganizations Organizations { get; private set; }
        public IPeople People { get; private set; }
        public ICardTokenization CardTokenization { get; private set; }
        public IHealth Health { get; private set; }

        public SDK(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Jobs = new Jobs(SDKConfiguration);

            Accounts = new Accounts(SDKConfiguration);

            Transfers = new Transfers(SDKConfiguration);

            Paychecks = new Paychecks(SDKConfiguration);

            Organizations = new Organizations(SDKConfiguration);

            People = new People(SDKConfiguration);

            CardTokenization = new CardTokenization(SDKConfiguration);

            Health = new Health(SDKConfiguration);
        }

        /// <summary>
        /// Initializes a new instance of the SDK with optional configuration parameters.
        /// </summary>
        /// <param name="security">The security configuration to use for API requests. If provided, this will be used as a static security configuration.</param>
        /// <param name="securitySource">A function that returns the security configuration dynamically. This takes precedence over the static security parameter if both are provided.</param>
        /// <param name="version">The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.<br/></param>
        /// <param name="serverIndex">The index of the server to use from the predefined server list. Must be between 0 and the length of the server list. Defaults to 0 if not specified.</param>
        /// <param name="environment">DailyPay REST API server</param>
        /// <param name="serverUrl">A custom server URL to use instead of the predefined server list. If provided with urlParams, the URL will be templated with the provided parameters.</param>
        /// <param name="urlParams">A dictionary of parameters to use for templating the serverUrl. Only used when serverUrl is provided.</param>
        /// <param name="client">A custom HTTP client implementation to use for making API requests. If not provided, the default SpeakeasyHttpClient will be used.</param>
        /// <param name="retryConfig">Configuration for retry behavior when API requests fail. Defines retry strategies, backoff policies, and maximum retry attempts.</param>
        /// <exception cref="Exception">Thrown when the serverIndex is out of range (less than 0 or greater than or equal to the server list length).</exception>
        public SDK(DailyPay.SDK.DotNet9.Models.Components.Security? security = null, Func<DailyPay.SDK.DotNet9.Models.Components.Security>? securitySource = null, long? version = null, int? serverIndex = null, ServerEnvironment? environment = null, string? serverUrl = null, Dictionary<string, string>? urlParams = null, ISpeakeasyHttpClient? client = null, RetryConfig? retryConfig = null)
        {
            if (serverIndex != null)
            {
                if (serverIndex.Value < 0 || serverIndex.Value >= SDKConfig.ServerList.Length)
                {
                    throw new Exception($"Invalid server index {serverIndex.Value}");
                }
            }

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<DailyPay.SDK.DotNet9.Models.Components.Security>? _securitySource = null;

            if(securitySource != null)
            {
                _securitySource = securitySource;
            }
            else if(security != null)
            {
                _securitySource = () => security;
            }

            SDKConfiguration = new SDKConfig(client)
            {
                Version = version,
                ServerIndex = serverIndex == null ? 0 : serverIndex.Value,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            if (environment != null)
            {
                SDKConfiguration.SetServerVariable("environment", ServerEnvironmentExtension.Value(environment.Value));
            }

            InitHooks();

            Jobs = new Jobs(SDKConfiguration);

            Accounts = new Accounts(SDKConfiguration);

            Transfers = new Transfers(SDKConfiguration);

            Paychecks = new Paychecks(SDKConfiguration);

            Organizations = new Organizations(SDKConfiguration);

            People = new People(SDKConfiguration);

            CardTokenization = new CardTokenization(SDKConfiguration);

            Health = new Health(SDKConfiguration);
        }

        private void InitHooks()
        {
            SDKConfiguration = SDKConfiguration.Hooks.SDKInit(SDKConfiguration);
        }

        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new SpeakeasyHttpClient());

            public SDKBuilder() { }

            public SDKBuilder WithServerIndex(int serverIndex)
            {
                if (serverIndex < 0 || serverIndex >= SDKConfig.ServerList.Length)
                {
                    throw new Exception($"Invalid server index {serverIndex}");
                }
                _sdkConfig.ServerIndex = serverIndex;
                return this;
            }

            public SDKBuilder WithEnvironment(ServerEnvironment environment)
            {
                _sdkConfig.SetServerVariable("environment", ServerEnvironmentExtension.Value(environment));
                return this;
            }

            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }

            public SDKBuilder WithVersion(long version)
            {
                _sdkConfig.Version = version;
                return this;
            }

            public SDKBuilder WithSecuritySource(Func<DailyPay.SDK.DotNet9.Models.Components.Security> securitySource)
            {
                _sdkConfig.SecuritySource = securitySource;
                return this;
            }

            public SDKBuilder WithSecurity(DailyPay.SDK.DotNet9.Models.Components.Security security)
            {
                _sdkConfig.SecuritySource = () => security;
                return this;
            }

            public SDKBuilder WithClient(ISpeakeasyHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            public SDK Build()
            {
              return new SDK(_sdkConfig);
            }

        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}