//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Requests
{
    using DailyPay.Models.Components;
    using DailyPay.Utils;
    using System;
    
    public class ListAccountsRequest
    {

        /// <summary>
        /// The version of the DailyPay API to use for this request. If not provided, the latest version of the API will be used.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=DailyPay-API-Version")]
        public long? Version { get; set; } = 3;

        /// <summary>
        /// Limit the results to documents related to a specific person
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[person.id]")]
        public string? FilterPersonId { get; set; }

        /// <summary>
        /// Limit the results to documents matching the specified account type.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[account_type]")]
        public FilterAccountType? FilterAccountType { get; set; }

        /// <summary>
        /// Limit the results to documents matching the specified account subtype.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter[subtype]")]
        public string? FilterSubtype { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible")]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=filter")]
        public string? FilterBy { get; set; }
    }
}