//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Openapi.Models.Errors
{
    using Newtonsoft.Json;
    using Openapi.Models.Components;
    using Openapi.Utils;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// The request contained an error
    /// </summary>
    public class TransferCreateError : Exception
    {

        /// <summary>
        /// A list of errors that occurred.
        /// </summary>
        [JsonProperty("errors")]
        public List<ErrorTransferCreateError> Errors { get; set; } = default!;
    }
}