//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Components
{
    using DailyPay.Models.Components;
    using DailyPay.Utils;
    using Newtonsoft.Json;
    
    public class PaycheckRelationships
    {

        [JsonProperty("person")]
        public PersonRelationship Person { get; set; } = default!;

        [JsonProperty("job")]
        public JobRelationship Job { get; set; } = default!;
    }
}