//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.Models.Errors
{
    using DailyPay.Models.Components;
    using DailyPay.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Invalid authentication credentials
    /// </summary>
    public class ErrorUnauthorized : Exception
    {

        /// <summary>
        /// A list of errors that occurred.
        /// </summary>
        [JsonProperty("errors")]
        public List<ErrorUnauthorizedError> Errors { get; set; } = default!;
    }
}