//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The subtype of the account.
    /// </summary>
    public enum AccountCreateAttributesDepositorySubtype
    {
        [JsonProperty("SAVINGS")]
        Savings,
        [JsonProperty("CHECKING")]
        Checking,
    }

    public static class AccountCreateAttributesDepositorySubtypeExtension
    {
        public static string Value(this AccountCreateAttributesDepositorySubtype value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static AccountCreateAttributesDepositorySubtype ToEnum(this string value)
        {
            foreach(var field in typeof(AccountCreateAttributesDepositorySubtype).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is AccountCreateAttributesDepositorySubtype)
                    {
                        return (AccountCreateAttributesDepositorySubtype)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum AccountCreateAttributesDepositorySubtype");
        }
    }

}