//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class AccountCreateAttributesType
    {
        private AccountCreateAttributesType(string value) { Value = value; }

        public string Value { get; private set; }

        public static AccountCreateAttributesType AccountCreateAttributesCard { get { return new AccountCreateAttributesType("AccountCreateAttributes_Card"); } }

        public static AccountCreateAttributesType AccountCreateAttributesDepository { get { return new AccountCreateAttributesType("AccountCreateAttributes_Depository"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(AccountCreateAttributesType v) { return v.Value; }
        public static AccountCreateAttributesType FromString(string v) {
            switch(v) {
                case "AccountCreateAttributes_Card": return AccountCreateAttributesCard;
                case "AccountCreateAttributes_Depository": return AccountCreateAttributesDepository;
                default: throw new ArgumentException("Invalid value for AccountCreateAttributesType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((AccountCreateAttributesType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// The details of the account.
    /// </summary>
    [JsonConverter(typeof(AccountCreateAttributes.AccountCreateAttributesConverter))]
    public class AccountCreateAttributes
    {
        public AccountCreateAttributes(AccountCreateAttributesType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public AccountCreateAttributesCard? AccountCreateAttributesCard { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public AccountCreateAttributesDepository? AccountCreateAttributesDepository { get; set; }

        public AccountCreateAttributesType Type { get; set; }
        public static AccountCreateAttributes CreateAccountCreateAttributesCard(AccountCreateAttributesCard accountCreateAttributesCard)
        {
            AccountCreateAttributesType typ = AccountCreateAttributesType.AccountCreateAttributesCard;

            AccountCreateAttributes res = new AccountCreateAttributes(typ);
            res.AccountCreateAttributesCard = accountCreateAttributesCard;
            return res;
        }
        public static AccountCreateAttributes CreateAccountCreateAttributesDepository(AccountCreateAttributesDepository accountCreateAttributesDepository)
        {
            AccountCreateAttributesType typ = AccountCreateAttributesType.AccountCreateAttributesDepository;

            AccountCreateAttributes res = new AccountCreateAttributes(typ);
            res.AccountCreateAttributesDepository = accountCreateAttributesDepository;
            return res;
        }

        public class AccountCreateAttributesConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(AccountCreateAttributes);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new AccountCreateAttributes(AccountCreateAttributesType.AccountCreateAttributesCard)
                    {
                        AccountCreateAttributesCard = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AccountCreateAttributesCard>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AccountCreateAttributesCard), new AccountCreateAttributes(AccountCreateAttributesType.AccountCreateAttributesCard), "AccountCreateAttributesCard"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new AccountCreateAttributes(AccountCreateAttributesType.AccountCreateAttributesDepository)
                    {
                        AccountCreateAttributesDepository = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AccountCreateAttributesDepository>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AccountCreateAttributesDepository), new AccountCreateAttributes(AccountCreateAttributesType.AccountCreateAttributesDepository), "AccountCreateAttributesDepository"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                AccountCreateAttributes res = (AccountCreateAttributes)value;

                if (res.AccountCreateAttributesCard != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AccountCreateAttributesCard));
                    return;
                }

                if (res.AccountCreateAttributesDepository != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AccountCreateAttributesDepository));
                    return;
                }
            }

        }

    }
}