//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// - `SETUP_REQUIRED` Direct deposit is not set up for this Job. Update this resource's relationships to set up direct deposit.<br/>
    /// - `SETUP_PENDING` A system action is still pending.<br/>
    /// - `SETUP_COMPLETE` Direct deposit is set up for this Job.
    /// </summary>
    public enum DirectDepositStatus
    {
        [JsonProperty("SETUP_REQUIRED")]
        SetupRequired,
        [JsonProperty("SETUP_PENDING")]
        SetupPending,
        [JsonProperty("SETUP_COMPLETE")]
        SetupComplete,
    }

    public static class DirectDepositStatusExtension
    {
        public static string Value(this DirectDepositStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static DirectDepositStatus ToEnum(this string value)
        {
            foreach(var field in typeof(DirectDepositStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DirectDepositStatus)
                    {
                        return (DirectDepositStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DirectDepositStatus");
        }
    }
}