//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// A code that indicates what went wrong.
    /// </summary>
    public enum ErrorUnexpectedErrorCode
    {
        [JsonProperty("UNEXPECTED_ERROR")]
        UnexpectedError,
    }

    public static class ErrorUnexpectedErrorCodeExtension
    {
        public static string Value(this ErrorUnexpectedErrorCode value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ErrorUnexpectedErrorCode ToEnum(this string value)
        {
            foreach(var field in typeof(ErrorUnexpectedErrorCode).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ErrorUnexpectedErrorCode)
                    {
                        return (ErrorUnexpectedErrorCode)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ErrorUnexpectedErrorCode");
        }
    }
}