//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// A list of links to resources that may be helpful in resolving the error.
    /// </summary>
    public class ErrorUnauthorizedErrorLinks
    {
        [JsonProperty("about")]
        public string? About { get; set; }
    }
}