//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Returns a healthcheck document.
    /// </summary>
    public class Health200
    {
        /// <summary>
        /// The status of the API.
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; } = default!;

        /// <summary>
        /// The version of the API.
        /// </summary>
        [JsonProperty("version")]
        public string Version { get; set; } = default!;
    }
}