//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Returns the job object.
    /// </summary>
    public class JobData
    {
        /// <summary>
        /// A job describes the financial relationship between a person and an organization.
        /// </summary>
        [JsonProperty("data")]
        public JobResource Data { get; set; } = default!;
    }
}