//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    
    public class OrganizationResource
    {

        [JsonProperty("type")]
        public string Type { get; } = "organizations";

        /// <summary>
        /// String identifier that is unique to this organization. You can safely assume the identifier to never exceed 64 characters.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        [JsonProperty("attributes")]
        public OrganizationAttributes Attributes { get; set; } = default!;

        [JsonProperty("links")]
        public OrganizationLinks Links { get; set; } = default!;
    }
}