//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    
    public class PersonResource
    {

        [JsonProperty("type")]
        public string Type { get; } = "people";

        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// A person is a record of someone known to DailyPay. There will only ever be one person record per human being.
        /// </summary>
        [JsonProperty("attributes")]
        public PersonAttributes Attributes { get; set; } = default!;

        [JsonProperty("links")]
        public PersonLinks Links { get; set; } = default!;
    }
}