//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Set the schedule for the transfer. If not set, the transfer will be processed immediately. <br/>
    /// A preview transfer will never send.
    /// </summary>
    public enum TransferAttributesSchedule
    {
        [JsonProperty("WITHIN_THIRTY_MINUTES")]
        WithinThirtyMinutes,
        [JsonProperty("NEXT_BUSINESS_DAY")]
        NextBusinessDay,
    }

    public static class TransferAttributesScheduleExtension
    {
        public static string Value(this TransferAttributesSchedule value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static TransferAttributesSchedule ToEnum(this string value)
        {
            foreach(var field in typeof(TransferAttributesSchedule).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is TransferAttributesSchedule)
                    {
                        return (TransferAttributesSchedule)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum TransferAttributesSchedule");
        }
    }
}