//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// An object representing a transfer of money from one account to another. <br/>
    /// Created when a person takes an advance against a future paycheck, or on a daily basis <br/>
    /// when we update estimated earnings based on current employment.
    /// </summary>
    public class TransferAttributes
    {
        /// <summary>
        /// Include this field to preview a transfer without sending it, to see, for example, the fee that would be charged. This will return the same response as a typical transfer request.<br/>
        /// When the preview field is true in the response to creating a transfer, that indicates no transfer was created.
        /// </summary>
        [JsonProperty("preview")]
        public bool? Preview { get; set; } = false;

        /// <summary>
        /// A monetary quantity expressed in units of the lowest denomination in the associated currency. For example, `{ amount: 7250, currency: 'USD' }` resolves to $72.50.
        /// </summary>
        [JsonProperty("amount")]
        public long Amount { get; set; } = default!;

        /// <summary>
        /// A three-letter ISO 4217 currency code. For example, `USD` for US Dollars, `EUR` for Euros, or `JPY` for Japanese Yen.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; } = default!;

        /// <summary>
        /// Set the schedule for the transfer. If not set, the transfer will be processed immediately. <br/>
        /// A preview transfer will never send.
        /// </summary>
        [JsonProperty("schedule")]
        public TransferAttributesSchedule Schedule { get; set; } = default!;

        /// <summary>
        /// The status of the transfer.
        /// </summary>
        [JsonProperty("status")]
        public TransferAttributesStatus Status { get; set; } = default!;

        /// <summary>
        /// An ISO 8601 timestamp denoting the receipt for the request.
        /// </summary>
        [JsonProperty("submitted_at")]
        public DateTime SubmittedAt { get; set; } = default!;

        /// <summary>
        /// An ISO 8601 date denoting a successful or unsuccessful resolution for the request.
        /// </summary>
        [JsonProperty("resolved_at", NullValueHandling = NullValueHandling.Include)]
        public DateTime? ResolvedAt { get; set; }

        /// <summary>
        /// A monetary quantity expressed in units of the lowest denomination in the associated currency. For example, `{ amount: 7250, currency: 'USD' }` resolves to $72.50.<br/>
        /// If a transfer incurs a fee, the fee will be deducted from the amount of the transfer.
        /// </summary>
        [JsonProperty("fee")]
        public long Fee { get; set; } = default!;
    }
}