//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet9.Models.Components
{
    using DailyPay.SDK.DotNet9.Models.Components;
    using DailyPay.SDK.DotNet9.Utils;
    using Newtonsoft.Json;

    public class TransferRelationships
    {
        /// <summary>
        /// Origin may be a reference to either a Paycheck or an Account.<br/>
        /// <br/>
        /// User-created transfers always originate from an Account with `account_type` `EARNINGS_BALANCE`.<br/>
        /// <br/>
        /// A transfer that originates from a Paycheck is a  <br/>
        /// system-created record that describes a credit of earnings to an account with `account_type` `EARNINGS_BALANCE`.
        /// </summary>
        [JsonProperty("origin", NullValueHandling = NullValueHandling.Include)]
        public Origin Origin { get; set; } = default!;

        /// <summary>
        /// The account to which funds are transferred. <br/>
        /// <br/>
        /// User-created transfers should have a destination Account with `account_type` `DEPOSITORY` or `CARD`.
        /// </summary>
        [JsonProperty("destination")]
        public AccountRelationship Destination { get; set; } = default!;

        [JsonProperty("person")]
        public PersonRelationship Person { get; set; } = default!;

        /// <summary>
        /// On user-created transfers, details the paychecks that are likely to be used to reimburse this transfer. <br/>
        /// <br/>
        /// The paychecks impacted, and final amount allocated from each paycheck is subject to change. <br/>
        /// See `final_funding_sources` for the final allocations.
        /// </summary>
        [JsonProperty("estimated_funding_sources")]
        public FundingSourcesRelationship EstimatedFundingSources { get; set; } = default!;

        /// <summary>
        /// On user-created transfers, details the paychecks that were used to reimburse this transfer and the amount allocated from each paycheck.<br/>
        /// <br/>
        /// If this relationship has members, its members and their values are immutable.
        /// </summary>
        [JsonProperty("final_funding_sources")]
        public FundingSourcesRelationship FinalFundingSources { get; set; } = default!;
    }
}