name: 'Publish .NET 9 SDK'
on:
  push:
    branches:
      - DEVREL-540
permissions:
  contents: read
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore ./src/DailyPay/DailyPay.csproj
      - name: Build SDK
        run: dotnet build ./src/DailyPay/DailyPay.csproj --configuration Release --no-restore
      - name: Pack SDK
        run: dotnet pack ./src/DailyPay/DailyPay.csproj --configuration Release --no-build --output ./nupkg
      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name github \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text
          dotnet nuget push ./nupkg/*.nupkg \
            --source github \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}