name: "Scan"

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch name to target scan on
        default: main
        required: true
        type: string
  workflow_call:
    inputs:
      branch_name:
        description: Branch name to target scan on
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write

env:
  GOPRIVATE: github.com/dailypay

jobs:
  scan:
    runs-on: k8s-general
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    strategy:
      matrix:
        branch: ["${{ inputs.branch_name }}"]
    steps:
      - name: configure git
        uses: dailypay/actions-commons/git-configure@v0

      - name: install dotnet 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: scan
        uses: jfrog/frogbot@v2
        env:
          JF_URL: https://artifactory.dailypay.com
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
        with:
          oidc-provider-name: github
          oidc-audience: dailypay-github
          version: ${{ vars.FROGBOT_VERSION }}


