name: 'Generate .NET 9 SDK'
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  generate-dotnet-sdk:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref || github.ref_name, 'sdk-regenerate-')"
    env:
      SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make git
      - name: Install Speakeasy CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/speakeasy-api/speakeasy/main/install.sh | bash
          echo "$HOME/.speakeasy/bin" >> $GITHUB_PATH
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      - name: Create new branch from DEVREL-539
        run: |
          BRANCH_NAME="sdk-regenerate-$(date +%s)"
          git fetch origin DEVREL-539
          git checkout -b $BRANCH_NAME origin/DEVREL-539
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
      - name: Generate SDK
        run: make generate-sdk
      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "no_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "no_changes=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Commit and push changes
        if: steps.check_changes.outputs.no_changes == 'false'
        run: |
          git add .
          git commit -m "chore: regenerate .NET 9 SDK"
          git push origin ${{ env.branch_name }}
      - name: Create Pull Request
        if: steps.check_changes.outputs.no_changes == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: DEVREL-539
          head: ${{ env.branch_name }}
          title: "chore: regenerate .NET 9 SDK"
          body: "This PR was automatically generated by a GitHub Action to regenerate the .NET 9 SDK with updated version info."